### ISSUE TITLE
Could you please add row/column labels?

### ISSUE THREAD

**Issue by yevgrashyn** [zilverline/battleship#1]
Hi,

Thanks a lot for the game! It is really useful to show the value of Iterative & Incremental development.

I want using it in my education program and want to let participants to guess where to shoot. To do this, I need to ask them which Row/Column they want to shoot.

Could you please add the row/column labels (i.e. A,B,C,D... and 1,2,3,4,) so one could say A4 meaning the specific cell.

Thank you in advance!

Regards, 
Tim

**Comment by Appesteijn** [comment]
@bforma Could you implement this on your hobby-friday? 😄

**Comment by bforma** [comment]
Will do! Releasing today.

**Comment by Appesteijn** [comment]
👍

**Comment by s0meone** [comment]
![image](https://cloud.githubusercontent.com/assets/82148/23296960/bc9bf782-fa77-11e6-9ee9-eb4698e41949.png)

**Comment by yevgrashyn** [comment]
Awesome job! Well done.

Could I use it on the public accessible site? 
http://zilverline.github.io/battleship/public/index.html

**Comment by Appesteijn** [comment]
@s0meone could you also rebase master into gh-pages? Then it automatically will be published.

**Comment by s0meone** [comment]
@yevgrashyn @Appesteijn Done. It's now live at http://zilverline.github.io/battleship/public/index.html

**Comment by Appesteijn** [comment]
Whoo!! Nice work!
